"""Import skills written in the Agent Skills format (agentskills.io) as builtin skills.

An Agent Skills package is a directory whose ``SKILL.md`` has YAML frontmatter
(``name``, ``description``, optionally ``license`` and ``compatibility``)
followed by Markdown instructions. An OE skill also needs ``when_to_use`` and
``category``, and lives at ``<category>/<name>.md``.

The marketing pack (github.com/superamped/ai-marketing-skills, MIT) writes
every description as "Use this skill to <what>. Trigger it <when>."; the two
halves become the OE ``description`` and ``when_to_use``. Its
``compatibility`` note ("Requires Keywords Everywhere MCP", …) is kept under
the skill's title. A footer credits the source, carries its copyright line
and marks the file as generated; the pack's full license is copied next to
the generated files. Edit the pack and re-run
``scripts/import_marketing_skills.py`` rather than editing generated files.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from openexecutive.knowledge.skills import (
    SkillFrontmatter,
    SkillParseError,
    parse_skill_text,
    serialize_skill,
)

MARKETING_PACK_NAME = "ai-marketing-skills"
MARKETING_PACK_URL = "https://github.com/superamped/ai-marketing-skills"

# The pack's LICENSE, copied next to the generated skills: MIT requires its
# notice in every copy, and the generated files ship in the package and image.
LICENSE_FILENAME = f"LICENSE-{MARKETING_PACK_NAME}.txt"

# Opens the last line of every generated file; that line is how an import
# recognizes the files it owns (and may overwrite or delete).
_GENERATED_MARKER = f"*Imported from [{MARKETING_PACK_NAME}]"

# Same fence format that skills.parse_skill_text accepts.
_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?(.*)$", re.DOTALL)
_DESCRIPTION_RE = re.compile(
    r"^Use this skill to (?P<what>.+?)\.\s+Trigger it (?P<when>.+?)\.?$", re.DOTALL
)
# Imported names must be lowercase kebab-case (the pack's own convention):
# names differing only in case would collide on Windows and macOS file systems.
_KEBAB_NAME_RE = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
_NO_REQUIREMENTS = "No special requirements."


def default_marketing_pack() -> Path:
    """The pack checked out next to OpenExecutive (the my_jarvis monorepo layout)."""
    # This file is .../OpenExecutive/packages/core/openexecutive/knowledge/…; a
    # flattened install (the Docker image's /app/openexecutive/…) is shallower,
    # and gets a path that doesn't exist rather than an IndexError.
    parents = Path(__file__).resolve().parents
    return parents[min(5, len(parents) - 1)] / MARKETING_PACK_NAME


def convert_skill(
    skill_md: str, *, category: str, source_path: str, copyright_line: str = ""
) -> tuple[str, str]:
    """Convert one ``SKILL.md`` to an OE skill; return ``(name, file text)``.

    *source_path* is the file's path inside the pack and *copyright_line* the
    pack's copyright notice, both cited in the footer. Raises SkillParseError
    when the file doesn't fit the pack's conventions or the result isn't a
    valid OE skill.
    """
    match = _FRONTMATTER_RE.match(skill_md)
    if not match:
        raise SkillParseError(f"{source_path}: missing YAML frontmatter")
    try:
        meta = yaml.safe_load(match.group(1)) or {}
    except yaml.YAMLError as e:
        raise SkillParseError(f"{source_path}: malformed YAML frontmatter: {e}") from e
    if not isinstance(meta, dict):
        raise SkillParseError(f"{source_path}: frontmatter is not a YAML mapping")
    name = str(meta.get("name", ""))
    if not _KEBAB_NAME_RE.fullmatch(name):
        raise SkillParseError(f"{source_path}: name {name!r} is not lowercase kebab-case")
    description = _DESCRIPTION_RE.match(str(meta.get("description", "")).strip())
    if not description:
        raise SkillParseError(
            f"{source_path}: description is not 'Use this skill to … Trigger it …'"
        )
    frontmatter = SkillFrontmatter(
        name=name,
        description=_sentence(description.group("what")),
        when_to_use=_sentence(description.group("when")),
        category=category,
    )

    body = match.group(2).strip()
    requirements = _requirements(meta.get("compatibility"))
    if requirements:
        body = _below_title(body, f"> **Requirements:** {requirements}")
    notice = f"{copyright_line}, " if copyright_line else ""
    footer = (
        f"{_GENERATED_MARKER}({MARKETING_PACK_URL}) — `{source_path}`. "
        f"{notice}{meta.get('license', 'see the pack')} License; full text in "
        f"`{LICENSE_FILENAME}`. Generated by `scripts/import_marketing_skills.py`: "
        "edit the pack and re-run it instead of editing this file.*"
    )
    text = serialize_skill(frontmatter, f"{body}\n\n---\n\n{footer}")
    parse_skill_text(text, Path(f"{name}.md"), source="builtin")
    return name, text


@dataclass
class ImportReport:
    written: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)


def import_pack(pack_root: Path, target_dir: Path, *, category: str = "marketing") -> ImportReport:
    """(Re)generate one OE skill in *target_dir* per ``skills/*/*/SKILL.md`` of the pack.

    Everything is converted and checked before anything is written. Generated
    files whose skill left the pack are deleted; hand-written skills in
    *target_dir* are never touched, and a pack skill whose name collides with
    one (ignoring case) aborts the import.
    """
    license_text = _read_license(pack_root)
    converted = _convert_pack(pack_root, category, _copyright_line(license_text))

    target_dir.mkdir(parents=True, exist_ok=True)
    existing = {path.stem.casefold(): path for path in target_dir.glob("*.md")}
    generated = {key for key, path in existing.items() if _is_generated(path)}
    collisions = sorted(
        name for name in converted if name in existing and name not in generated
    )
    if collisions:
        raise SkillParseError(f"pack skills collide with hand-written skills: {collisions}")

    report = ImportReport()
    for name, text in converted.items():
        path = target_dir / f"{name}.md"
        if path.exists() and path.read_text(encoding="utf-8") == text:
            report.unchanged.append(name)
            continue
        path.write_text(text, encoding="utf-8", newline="\n")
        report.written.append(name)
    for key in sorted(generated - converted.keys()):
        existing[key].unlink()
        report.removed.append(existing[key].stem)
    (target_dir / LICENSE_FILENAME).write_text(license_text, encoding="utf-8", newline="\n")
    return report


def _convert_pack(pack_root: Path, category: str, copyright_line: str) -> dict[str, str]:
    converted: dict[str, str] = {}
    for skill_md in sorted(pack_root.glob("skills/*/*/SKILL.md")):
        source_path = skill_md.relative_to(pack_root).as_posix()
        name, text = convert_skill(
            skill_md.read_text(encoding="utf-8"),
            category=category,
            source_path=source_path,
            copyright_line=copyright_line,
        )
        if name in converted:
            raise SkillParseError(f"{source_path}: duplicate skill name {name!r}")
        converted[name] = text
    return converted


def _read_license(pack_root: Path) -> str:
    path = pack_root / "LICENSE"
    if not path.is_file():
        raise SkillParseError(f"{pack_root}: no LICENSE file — the notice must ship with the skills")
    return path.read_text(encoding="utf-8")


def _copyright_line(license_text: str) -> str:
    return next(
        (line.strip() for line in license_text.splitlines() if line.strip().startswith("Copyright")),
        "",
    )


def _is_generated(path: Path) -> bool:
    lines = path.read_text(encoding="utf-8").rstrip().splitlines()
    return bool(lines) and lines[-1].startswith(_GENERATED_MARKER)


def _requirements(compatibility: object) -> str:
    """The pack's compatibility note without its "no requirements" boilerplate."""
    text = " ".join(str(compatibility or "").split())
    if text.startswith(_NO_REQUIREMENTS):
        text = text[len(_NO_REQUIREMENTS):].strip()
    return text


def _sentence(fragment: str) -> str:
    fragment = " ".join(fragment.split())
    return fragment[:1].upper() + fragment[1:] + ("" if fragment.endswith(".") else ".")


def _below_title(body: str, block: str) -> str:
    """Insert *block* after the body's leading ``# Title`` line (or at the top)."""
    first, _, rest = body.partition("\n")
    if first.startswith("# "):
        return f"{first}\n\n{block}\n\n{rest.lstrip()}".rstrip()
    return f"{block}\n\n{body}"
